# Generated by Django 3.1.4 on 2021-02-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='verified',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10),
        ),
    ]
