# Generated by Django 3.1.4 on 2021-01-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Seller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seller'),
        ),
    ]
