# Generated by Django 3.1.4 on 2021-01-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210130_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Buyer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Seller',
        ),
    ]
