# Generated by Django 3.1.4 on 2021-02-03 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210203_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date_reviewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
