# Generated by Django 3.1.4 on 2021-03-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_added_skills_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Added_skills_service',
        ),
    ]
