# Generated by Django 3.1.4 on 2021-02-12 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_category_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_replies',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.requests'),
        ),
    ]
