# Generated by Django 3.1.4 on 2021-01-13 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210104_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='_customuser_contacts_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
