# Generated by Django 3.1.4 on 2021-02-03 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reviews_date_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service'),
        ),
    ]
