# Generated by Django 3.1.4 on 2021-02-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210212_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_replies',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requests'),
        ),
    ]
