# Generated by Django 3.1.4 on 2021-01-13 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.buyer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seller'),
        ),
    ]
