# Generated by Django 3.1.4 on 2021-02-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210212_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
