# Generated by Django 3.1.4 on 2021-02-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210213_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_acc',
            field=models.FloatField(default=0),
        ),
    ]
