# Generated by Django 3.1.4 on 2021-02-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210203_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='star_rating',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service'),
        ),
    ]
