# Generated by Django 3.1.4 on 2021-02-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_star_rating_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star_rating',
            name='rating_star',
            field=models.IntegerField(),
        ),
    ]
