# Generated by Django 3.1.4 on 2021-02-14 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210213_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer_notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Request_replies', models.ManyToManyField(to='core.Request_replies')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buyer')),
            ],
        ),
    ]
