# Generated by Django 3.1.4 on 2021-02-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_buyer_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer_notifications',
        ),
    ]
