# Generated by Django 3.1.4 on 2021-02-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210205_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='ordered',
            field=models.CharField(choices=[('rejected', 'rejected'), ('not_ordered', 'ordered'), ('ordered', 'ordered'), ('delivered', 'delivered')], default='not_ordered', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.delivery_days'),
        ),
    ]
