# Generated by Django 3.1.4 on 2021-02-14 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_buyer_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer_notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_replies', models.ManyToManyField(to='core.Request_replies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
