# Generated by Django 3.1.4 on 2021-02-14 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_buyer_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer_notifications',
            name='request_replies',
        ),
        migrations.AddField(
            model_name='buyer_notifications',
            name='request_replies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.request_replies'),
        ),
    ]
