# Generated by Django 3.1.4 on 2021-02-14 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210214_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_notifications',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
