# Generated by Django 3.1.4 on 2021-02-15 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_buyer_notifications_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply_notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_replies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.request_replies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Buyer_notifications',
        ),
    ]
