# Generated by Django 3.1.4 on 2021-02-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_notifications_review_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_notifications',
            old_name='review_user',
            new_name='review',
        ),
    ]
