# Generated by Django 3.1.4 on 2021-02-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_thread_chatt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='chatt',
        ),
    ]
