# Generated by Django 3.1.4 on 2021-02-23 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210222_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='timestamp2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
