# Generated by Django 3.1.4 on 2021-02-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210228_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='chatt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_chat', to='chat.chatmessage'),
        ),
    ]
