# Generated by Django 3.1.4 on 2021-02-24 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_timestamp2'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='timestamp2',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
