# Generated by Django 3.1.4 on 2021-02-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210228_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='chatt',
        ),
    ]
